FROM nginx:1.22
WORKDIR /home/zakaria/BaseApp/frontend
COPY nginx.conf /home/zakaria/BaseApp/frontend/.
COPY index.html /home/zakaria/BaseApp/frontend/.
COPY style.css /home/zakaria/BaseApp/frontend/.
EXPOSE 80

